### ISSUE TITLE
Add Finsweet Cookie Consent

### ISSUE THREAD

**Issue by dumkydewilde** [dumkydewilde/consentcrawl#8]
Test site: https://get-it-made.co.uk/
Vendor: https://finsweet.com/cookie-consent

```
- id: finsweet-webflow
  name: Finsweet Cookie Consent for webflow
  brand: Finsweet
  actions:
    - type: css-selector
      value: "[fs-cc=allow]"
```
